<?php

use Illuminate\Database\Seeder;
use Illuminate\Database\Eloquent\Model;

class AdminActionTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //
        DB::table('admin_actions')->insert([
            [
                "parent_id" => 0,
                "code" => "game",
                "lang" => "game",
                "route" => "",
                "param" => "",
                "enable" => 0,
                "remark" => "",
                "icon" => "gamepad",
                "list_order" => 10,
            ],
            [
                "parent_id" => 0,
                "code" => "news",
                "lang" => "news",
                "route" => "",
                "param" => "",
                "enable" => 0,
                "remark" => "",
                "icon" => "newspaper-o",
                "list_order" => 10,
            ],
            [
                "parent_id" => 0,
                "code" => "user",
                "lang" => "user",
                "route" => "",
                "param" => "",
                "enable" => 0,
                "remark" => "",
                "icon" => "users",
                "list_order" => 10,
            ],
            [
                "parent_id" => 0,
                "code" => "order",
                "lang" => "order",
                "route" => "",
                "param" => "",
                "enable" => 0,
                "remark" => "",
                "icon" => "shopping-cart",
                "list_order" => 10,
            ],
            [
                "parent_id" => 0,
                "code" => "permissions",
                "lang" => "permissions",
                "route" => "",
                "param" => "",
                "enable" => 0,
                "remark" => "",
                "icon" => "wrench",
                "list_order" => 10,
            ],
            [
                "parent_id" => 0,
                "code" => "system",
                "lang" => "system",
                "route" => "",
                "param" => "",
                "enable" => 1,
                "remark" => "",
                "icon" => "cogs",
                "list_order" => 10,
            ],
            [
                "parent_id" => 1,
                "code" => "categoryManage",
                "lang" => "categoryManage",
                "route" => "",
                "param" => "",
                "enable" => 1,
                "remark" => "",
                "icon" => "book",
                "list_order" => 10,
            ],
            [
                "parent_id" => 1,
                "code" => "addCategory",
                "lang" => "addCategory",
                "route" => "",
                "param" => "",
                "enable" => 1,
                "remark" => "",
                "icon" => "plus",
                "list_order" => 10,
            ],
            [
                "parent_id" => 1,
                "code" => "gameModelManage",
                "lang" => "gameModelManage",
                "route" => "",
                "param" => "",
                "enable" => 1,
                "remark" => "",
                "icon" => "list-ol",
                "list_order" => 10,
            ],
            [
                "parent_id" => 1,
                "code" => "addGameModel",
                "lang" => "addGameModel",
                "route" => "",
                "param" => "",
                "enable" => 1,
                "remark" => "",
                "icon" => "plus-circle",
                "list_order" => 10,
            ],
            [
                "parent_id" => 2,
                "code" => "categoryManage",
                "lang" => "categoryManage",
                "route" => "",
                "param" => "",
                "enable" => 1,
                "remark" => "",
                "icon" => "list-ol",
                "list_order" => 10,
            ],
            [
                "parent_id" => 2,
                "code" => "newsList",
                "lang" => "newsList",
                "route" => "",
                "param" => "",
                "enable" => 1,
                "remark" => "",
                "icon" => "list",
                "list_order" => 10,
            ],
            [
                "parent_id" => 2,
                "code" => "addNews",
                "lang" => "addNews",
                "route" => "",
                "param" => "",
                "enable" => 1,
                "remark" => "",
                "icon" => "plus",
                "list_order" => 10,
            ],
            [
                "parent_id" => 2,
                "code" => "addSinglePage",
                "lang" => "addSinglePage",
                "route" => "",
                "param" => "",
                "enable" => 1,
                "remark" => "",
                "icon" => "plus-circle",
                "list_order" => 10,
            ],
            [
                "parent_id" => 3,
                "code" => "userManage",
                "lang" => "userManage",
                "route" => "",
                "param" => "",
                "enable" => 1,
                "remark" => "",
                "icon" => "users",
                "list_order" => 10,
            ],
            [
                "parent_id" => 3,
                "code" => "companyList",
                "lang" => "companyList",
                "route" => "",
                "param" => "",
                "enable" => 1,
                "remark" => "",
                "icon" => "building",
                "list_order" => 10,
            ],
            [
                "parent_id" => 5,
                "code" => "adminManage",
                "lang" => "adminManage",
                "route" => "",
                "param" => "",
                "enable" => 1,
                "remark" => "",
                "icon" => "users",
                "list_order" => 10,
            ],
            [
                "parent_id" => 5,
                "code" => "roleManage",
                "lang" => "roleManage",
                "route" => "",
                "param" => "",
                "enable" => 1,
                "remark" => "",
                "icon" => "book",
                "list_order" => 10,
            ],
            [
                "parent_id" => 6,
                "code" => "config",
                "lang" => "systemConfig",
                "route" => "",
                "param" => "",
                "enable" => 1,
                "remark" => "",
                "icon" => "cog",
                "list_order" => 10,
            ],
            [
                "parent_id" => 6,
                "code" => "menuManage",
                "lang" => "menuManage",
                "route" => "",
                "param" => "",
                "enable" => 0,
                "remark" => "",
                "icon" => "book",
                "list_order" => 10,
            ],
            [
                "parent_id" => 6,
                "code" => "addMenu",
                "lang" => "addMenu",
                "route" => "",
                "param" => "",
                "enable" => 0,
                "remark" => "",
                "icon" => "plus",
                "list_order" => 10,
            ]
        ]);
    }
}
